### ISSUE TITLE
StreamlitAPIException: No such component directory: 'C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit_execute\frontend\dist'

### ISSUE THREAD

**Issue by Shen-Ming-Hong** [bouzidanas/streamlit-execute#1]
**Description:**
I encountered an issue while using the `streamlit-execute` package. Upon running the provided example code, I received a `StreamlitAPIException` indicating that there is no such component directory.

**Error Details:**
```
StreamlitAPIException: No such component directory: 'C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit_execute\frontend\dist'

Traceback:
File "E:\test.py", line 2, in <module>
    from streamlit_execute import init
File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit_execute\__init__.py", line 73, in <module>
    _component_func_init = components.declare_component("streamlit_execute_init", path=build_dir_init)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Steps to Reproduce:**
1. Installed the package using `pip install streamlit-execute`.
2. Created a new test project and added the example code as follows:
   ```python
   import streamlit as st
   from streamlit_execute import init

   # Execute code
   response = init("print('Hello World!')")
   st.write(response)
   ```
3. Ran the script and encountered the error mentioned above.

**System Information:**
- Operating System: Windows 11
- Python Version: 3.11
- Streamlit Version: 1.35.0
- streamlit-execute Version: 0.0.3

**Additional Context:**
I followed the exact steps provided in the documentation and the error still occurred. It seems the component directory `frontend/dist` is missing from the installation package.

**Expected Behavior:**
The example code should execute without errors and display "Hello World!" in the Streamlit app.

Please let me know if there are any additional steps I can take to resolve this issue or if further information is needed.

Thank you!

**Comment by bouzidanas** [comment]
Hi @Shen-Ming-Hong 

Nice catch! I believe the code did work before but I think I deleted the build (dist) directory and forgot to re-build before submitting new version to PyPi. I will fix soon!

Thank you for trying it out!

**Comment by bouzidanas** [comment]
Fyi, there is a minor issue with the connection function and I have figured out the problem and I will fix it with the next couple of days if not today.

**Comment by bouzidanas** [comment]
Hey @Shen-Ming-Hong,

Good news. Everything should work now. What happened was that I forgot to edit the manifest when I replaced it so streamlit was looking for the wrong name of the component. Also, the connect issue is also fixed.

Make sure to update to [version 0.1.0](https://pypi.org/project/streamlit-execute/0.1.0/) or later to get all the fixes!
